# Generated by Django 6.0.6 on 2026-07-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='歌手ID')),
                ('name', models.CharField(max_length=200, verbose_name='歌手姓名')),
                ('image_url', models.CharField(max_length=200, verbose_name='歌手图片地址')),
                ('desc', models.TextField(blank=True, default='', null=True, verbose_name='歌手简介')),
                ('source_url', models.URLField(verbose_name='歌手原始链接')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='歌曲ID')),
                ('name', models.CharField(max_length=200, verbose_name='歌曲名')),
                ('image_url', models.CharField(max_length=200, verbose_name='歌曲图片地址')),
                ('source_url', models.URLField(verbose_name='歌曲原始链接')),
                ('lyrics', models.TextField(blank=True, default='', null=True, verbose_name='歌曲歌词')),
                ('singers', models.ManyToManyField(related_name='songs', to='web.singer')),
            ],
        ),
    ]
