# Generated by Django 6.0.6 on 2026-07-07 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='评论ID')),
                ('name', models.CharField(max_length=200, verbose_name='昵称')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='评论内容')),
                ('create_time', models.DateField(verbose_name='创建日期')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='web.song')),
            ],
        ),
    ]
