# Generated by Django 6.0.6 on 2026-07-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='song',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
